---
kind: Service
apiVersion: v1
metadata:
  name: doks-example3
spec:
  type: LoadBalancer
  selector:
    app: doks-example3
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: doks-example3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: doks-example3
  template:
    metadata:
      labels:
        app: doks-example3
    spec:
      containers:
      - name: nginx
        image: digitalocean/doks-example
        ports:
        - containerPort: 80
          protocol: TCP
