name: ingress update

on:
  push:
    paths:
    - '.kubeconf/ingress/ingress.yaml'

jobs:
  build:
    name: update
    runs-on: ubuntu-latest
    steps:

    - name: Checkout master
      uses: actions/checkout@master


    - name: Save DigitalOcean kubeconfig
      uses: digitalocean/action-doctl@master
      env:
        DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      with:
        args: kubernetes cluster kubeconfig show mmm > $GITHUB_WORKSPACE/.kubeconfig

    - name: Deploy to DigitalOcean Kubernetes
      run: kubectl --kubeconfig=$GITHUB_WORKSPACE/.kubeconfig apply -f $GITHUB_WORKSPACE/.kubeconf/ingress/ingress.yml
